[package]
name = "rust_interface_file_generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_attributes = {path = "../rust_interface_file_generator/gen_attributes"}
syn = { version = "*", features = ["full","extra-traits","derive"] }
derive-new = "*"
Inflector = "*"
